name: build-actions
on: [push]
jobs:
  pre-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run tsc
