name: build-actions
on: [push]
jobs:
  pre-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: frontend npm install
        run: cd frontend
        run: npm install
      - name: frontend lint
        run: cd frontend
        run: npm run lint
      - name: frontend tsc
        run: cd frontend
        run: npm run tsc
